connection_string: 'jdbc:mysql://127.0.0.1/minecraft?user=minecraft&password=minecraft'
questions:
    - 'Hallo Gast, ein Freischalter stellt dir jetzt Fragen. Du brauchst einfach nur in den Chat schreiben. Du kannst jederzeit die Freischaltung mit /exit abbrechen.'
    - 'Hast du die Regeln gelesen und verstanden?'
    - 'Warum sind die in den Regeln gennanten Mods verboten?'
    - 'Nenne einige Dinge die nicht im Serverchat stehen sollen.'
    - 'Wie führst du Privatgespräche?'
    - 'Nenne drei Dinge die nicht gebaut werden dürfen.'
    - 'Wie kann man eine Zone erstellen?'
    - 'Was hilft dir beim Erstellen einer Zone?'
    - 'Welche zwei Orte stehen extra zur Rohstoffbeschaffung zur Verfügung?'
    - 'Was machst du wen du einen Bug entdeckst?'
    - 'Hast du noch irgendwelche Fragen?'
    - 'Dann schalte ich dich nun frei. Viel Spaß!'
unlock_group: 'player'
send_global_message: true
global_message: '["",{"text":"Willkommen auf dem Server, ","color":"yellow"},{"text":"?target_name","color":"gray"},{"text":"!","color":"yellow"}]'